apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloservice
  labels:
    app: spring-boot-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-k8s
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
      - name: hello-service
        image: hello-service
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: helloservice-svc
  labels:
    app: spring-boot-k8s
spec:
  type: NodePort
  ports:
  - port: 31234
    nodePort: 30123
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: spring-boot-k8s
